version: '3'

services:
  scraper_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - mysql_db
    environment:
      DJANGO_SETTINGS_MODULE: scrapper.settings
      DATABASE_URL: mysql://root:password@mysql_db:3306/scrapper
    volumes:
      - ./:/app
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'scrapper'
      MYSQL_USER: 'scrapper_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"


volumes:
  mysql_data: