# Generated by Django 5.0.4 on 2024-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cufe', models.CharField(max_length=100)),
                ('events', models.JSONField(verbose_name='Eventos de la factura')),
                ('issuer_name', models.CharField(max_length=50, verbose_name='Nombre del emisor')),
                ('issuer_nit', models.CharField(max_length=50, verbose_name='Nit del emisor')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='Nombre del receptor')),
                ('receiver_nit', models.CharField(max_length=50, verbose_name='Nit del receptor')),
                ('representation', models.CharField(max_length=100, verbose_name='Link de representación Grafica')),
            ],
        ),
    ]
