# Generated by Django 5.0.4 on 2024-05-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='representation',
            field=models.CharField(max_length=255, verbose_name='Link de representación Grafica'),
        ),
    ]
