# Generated by Django 5.0.4 on 2024-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_representation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cufe',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
